Expanded documentation for tracing fields
elastic/ecs pull request #1128
Opened 2020-11-17 12:12 UTC by sgryphon

Additional usage documentation for tracing fields, with a longer explanation of trace.id, span.id, and how they are related, and the correlation purpose of each.

Documentation would not reproduce the diagrams inline, so added to the optional docs/usages/<field>.asciidoc file.

Addresses issue #998

2020-11-18 13:08 UTC, sgryphon commented
@webmat I see you added the label 1.9.0, which I am guessing means version 1.9.   This is only additional documentation, not an actual schema change, so from SemVer point of view it is can be a patch version 1.7, as it is still fully compatible with 1.7

2020-11-18 14:08 UTC, webmat commented
@sgryphon Yeah we did that tagging as part of regular planning and figuring what we have time for when. We hadn't noticed that you were actually contributing the documentation page itself.

This is great, thank you for submitting that :-)

We will review shortly, and we may indeed backport this all the way back to 1.7, so that the documentation page comes to life before the next release.

2020-11-18 14:10 UTC, webmat commented
@elasticmachine, run elasticsearch-ci/docs

2020-11-18 15:44 UTC, webmat commented
The doc page can now be previewed at https://ecs_1128.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-tracing-usage.html :-)

2020-11-24 19:12 UTC, webmat commented
@axw Do you feel like this doc page captures the discussion in #998?

2020-11-25 02:50 UTC, axw reviewed
Thanks @sgryphon! This looks pretty good overall.

I'm happy to have this usage page. There are some discrepancies with Elastic APM which, along with ECS loggers, is (AFAIK) the only thing using these fields at the moment. I think it's important that we make some adjustments to avoid confusion.

@felixbarny @bmorelli25 any thoughts, concerns?

2021-01-21 08:39 UTC, sgryphon commented on docs/usage/tracing.asciidoc
> +A distributed trace is a set of messages, triggered as a result of a single logical operation, consolidated across
Sounds great. Changed.

2021-01-21 09:10 UTC, sgryphon commented on schemas/tracing.yml
> +        A span represents an operation within a trace, such as a request to another service, or a database query.
Fixed

2021-01-21 09:10 UTC, sgryphon commented on docs/usage/tracing.asciidoc
> +------------------------------------------------------------------
Updated the text to better align with APM and added the link to APM transactions. Modified the diagrams to indicate transaction spans (and service boundaries).

2021-01-25 08:47 UTC, sgryphon commented
Pull request has been updated based on feedback. Please review and let me know if there is anything else needed before it can be merged. Thanks.

2021-01-25 13:24 UTC, axw submitted a review, later dismissed
Thanks for the updates @sgryphon. LGTM!

2021-01-25 17:24 UTC, bmorelli25 commented
@elasticmachine, run elasticsearch-ci/docs

2021-01-25 22:48 UTC, bmorelli25 requested changes
Thanks again for putting this together! I have a few grammar/spelling recommendations. Everything is open for discussion, so feel free to let me know if you disagree with anything!

I'll mock up some graphics for this right now.

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +A trace describes the individual operations, and their causality, that ensue as a result of a single logical
```suggestion
A trace describes the individual operations and their causality that ensue from a single logical 
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +For example, a distributed trace may be initiated when someone presses a button to start an action on a website - in this example,
It's subtle, but this should be an em dash

```suggestion
For example, a distributed trace may be initiated when someone presses a button to start an action on a website – in this example, 
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +the trace will represent calls made between the downstream services that handled the chain of requests initiated by this
```suggestion
the trace represents calls made between the downstream services that handled the chain of requests initiated by this 
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +button being pressed.
```suggestion
button press.
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +transactions have additional attributes associated with them
```suggestion
transactions also have additional attributes associated with them.
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +(for more detail see https://www.elastic.co/guide/en/apm/get-started/current/transactions.html).
We use attributes for internal links. This ensures links are always correct -- even if pages move.

```suggestion
Learn more about transactions in {apm-overview-ref-v}/transactions.html[APM Transactions].
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +Usually a transaction corresponds to the top level request to a component. Sometimes a component may break up processing into
```suggestion
Usually, a transaction corresponds to the top-level request to a component. Sometimes a component may break up processing into 
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +The spans (and transactions) have a parent/child relationship with other spans and form a tree (or directed acylic grapph),
Is this an either-or? I think it'd be more clear if we said "also known as" instead.

```suggestion
The spans (and transactions) have a parent/child relationship with other spans and form a tree (also known as a directed acyclic graph), 
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +with each span (or transaction), except the root, having a parent.
```suggestion
with each span or transaction, except the root, having a parent.
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +If following the https://www.w3.org/TR/trace-context/[W3C Trace Context Recommendation] then
```suggestion
If you're following the https://www.w3.org/TR/trace-context/[W3C Trace Context Recommendation],
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +the https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html[APM Distributed Tracing] documentation.
We've already used APM on this page, so I think only using the initialism is acceptable.

```suggestion
For correlation with Elastic APM, see
{apm-overview-ref-v}/distributed-tracing.html[APM Distributed Tracing].
```

2021-01-25 22:48 UTC, bmorelli25 commented on docs/usage/tracing.asciidoc
> +------------------------------------------------------------------
I'm not a fan of how these render. Let me mock up some graphics to replace these. Give me an hour.

2021-01-26 00:18 UTC, bmorelli25 commented
Here's what I'm thinking for the causal and temporal graphics. Open to feedback.

![causal-span-trace](https://user-images.githubusercontent.com/5618806/105782227-f7767c00-5f28-11eb-9411-b10e05499f09.png)

![temporal-span-trace](https://user-images.githubusercontent.com/5618806/105782231-fcd3c680-5f28-11eb-9f7a-b662f7f79892.png)

2021-02-01 20:48 UTC, ebeahan commented
Thanks, @sgryphon, for taking on authoring this content!  The functionality to add the usage docs was added only recently, so it's great to see folks contributing already. 😄 

Also, thanks to @axw and @bmorelli25 for the reviews and feedback. [These graphics](https://github.com/elastic/ecs/pull/1128#issuecomment-767196715) look amazing! ❤️  💯 

From an ECS-perspective, I do have reservations that this content is too focused on terminology and concepts and not focused enough on how to use/populate the ECS fields themselves. I prefer directing users to the APM docs' relevant sections as the more definitive reference for definitions and concepts. The ECS usage docs can then focus on applying the concepts with real-world examples using the `tracing.*` fields.

Those types of extended examples will help tie together concepts better for ECS users when mapping their own data sources. Some of the original questions from https://github.com/elastic/ecs/issues/998 were "How do these [fields] work together?", and I want to ensure that remains in focus here.

2021-02-03 00:55 UTC, sgryphon commented
> Here's what I'm thinking for the causal and temporal graphics. Open to feedback.
 
My question about the graphics are how are they generated?  Using ASCII is viewable even in text output.

Mostly for diagrams I use something like PlantUML, to specify the diagram in text (under version control) and then generate the image.

But if you prefer straight images that is okay. I will create some SVG of the able, which are then more easily trackable in version control for changes.

2021-02-03 01:22 UTC, sgryphon commented
> Those types of extended examples will help tie together concepts better for ECS users when mapping their own data sources. Some of the original questions from #998 were "How do these [fields] work together?", and I want to ensure that remains in focus here.

Okay, I can expand on "how to populate the ECS fields".

I'll see what I can come up with for a general solution (e.g. users mapping their own sources), but implementations might end up being technology specific, e.g. how you would populate them in using the built in TraceContext support in .NET would be very different than if using the Elastic APM agent in Python, etc.

2022-02-28 22:46 UTC, bmorelli25 commented
Closing this and moving documentation to the APM Guide. Tracking in https://github.com/elastic/observability-docs/issues/817.

2022-02-28 22:46 UTC, closed without merging