[RFC] `text` to `match_only_text` field type migration - Stage 2
elastic/ecs pull request #1522
Opened 2021-07-15 17:36 UTC by ebeahan

### Summary

Continuing onto Stage 2 with this proposal for migrating `text` type fields to use the `match_only_text` data type.

`match_only_text` is being introduced in Elasticsearch 7.14.

Stage 2 (Candidate) Criteria:

- [ ] Opened pull request for this draft revising the existing proposal
- [ ] Completed field definitions
- [ ] Included a real world example source document
- [ ] Identifies scope of impact of changes to ingestion mechanisms (e.g. beats/logstash), usage mechanisms (e.g. Kibana applications, detections), and the ECS project (e.g. docs, tooling)
- [ ] Subject matter experts weighed in on technical utility of field definitions in the pull request

[Preview of markdown proposal](https://github.com/ebeahan/ecs/blob/rfc/0023/stage-2/rfcs/text/0023-match_only_text-data-type.md)

2021-07-16 09:25 UTC, jpountz approved these changes

2021-07-16 13:44 UTC, kgeller approved these changes

2021-07-19 15:47 UTC, epixa requested changes

2021-07-19 15:47 UTC, epixa commented on rfcs/text/0023-match_only_text-data-type.md
> +* Stage 2: https://github.com/elastic/ecs/pull/NNN
```suggestion
* Stage 2: https://github.com/elastic/ecs/pull/1522
```

2021-07-19 20:52 UTC, merged