Pe ordering fix
elastic/ecs pull request #1605
Opened 2021-09-09 14:35 UTC by kgeller

https://elastic.slack.com/archives/C8L4TMJGJ/p1631024860024500

Just like in https://github.com/elastic/ecs/pull/1603, we realized we were missing pe.* under threat.indicator.file and `threat.enrichments.indicator.file' .

2021-09-09 21:44 UTC, rylnd requested changes
I think we should delete `pe` as a top-level field on `indicator`; otherwise this looks good to me.

2021-09-09 21:44 UTC, rylnd commented on generated/ecs/ecs_nested.yml
> +  - full: threat.indicator.pe
I think we want these gone, right? `pe` will be nested under `file` or `process`, but not as a sibling

2021-09-09 21:48 UTC, rylnd approved these changes
Disregard the last review, it looks like you already made my proposed changes in #1604. :shipit: 

I appreciate the logically separated PRs; I do not envy merging them back together, though!

2021-09-16 17:21 UTC, epixa approved these changes
LGTM

2021-09-16 18:46 UTC, merged