removing es6 support in ecs 8.0
elastic/ecs pull request #1680
Opened 2021-12-06 19:29 UTC by kgeller

2021-12-07 18:53 UTC, kgeller commented
@elasticmachine run elasticsearch-ci/docs

2021-12-08 14:21 UTC, kgeller commented
@elasticmachine run elasticsearch-ci/docs

2021-12-09 20:44 UTC, ebeahan requested changes

2021-12-09 20:44 UTC, ebeahan commented on CHANGELOG.next.md
> +* Remove template generation for ES6. #1680
If we backport to 8.0, let's move this under the 8.0.0 changelog.

2021-12-09 20:44 UTC, ebeahan commented on scripts/generators/es_template.py
> -            fallback_type = TYPE_FALLBACKS.get(details['type'])
Is anything still using `TYPE_FALLBACKS`?

If not, that global can be cleared out.

2021-12-09 20:44 UTC, ebeahan commented on scripts/generators/es_template.py
> -                    field_or_multi_field_datatype_defaults(mappings[name]['fields'][field_name])
This import from `schema.cleaner` might be removable `field_or_multi_field_datatype_defaults` now.

2021-12-09 20:44 UTC, ebeahan commented on scripts/generators/es_template.py
> -        mappings_section = copy.deepcopy(mappings_section)
I think `copy` is now another unused import too.

2021-12-14 19:33 UTC, ebeahan approved these changes
Thanks for making the changes - LGTM! 🚀

2021-12-14 20:47 UTC, merged