Mapping parameters
elastic/ecs pull request #2084
Opened 2022-10-31 15:54 UTC by ralphm

When attempting to create a custom mapping for a `date` (multi-)field, I found that the ECS tooling doesn't currently support providing the `ignore_malformed` and `format` mapping parameters. Even though there is some limited support for certain parameters, these are not consistent between the main field mapping and the multi-field mapping. E.g. the `normalizer` parameter is only available for multi-fields.

Instead of implementing specific parameters for my use case, this PR adds a new property `parameters` to provide any mapping parameter, both for the main field and for multi-fields, along with a minimal test for the multi-field generation code. The existing code can remain as-is, with the minimal sanity checking that is in place, for backwards compatibility.

2023-01-31 12:41 UTC, ralphm commented
Any chance this can get a review? The merge conflict is trivial, and I'll be happy to resolve that when the time comes.

2023-02-28 15:11 UTC, kgeller requested changes
@ralphm this looks like a great add. Once the merge conflict is resolved, I will approve and merge.

2023-02-28 18:17 UTC, kgeller approved these changes

2023-02-28 18:17 UTC, merged

2023-02-28 19:47 UTC, ralphm commented
Thanks, @kgeller!